// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RequestContext
	ResponseContext
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestContext struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Method  string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Header  string `protobuf:"bytes,3,opt,name=header" json:"header,omitempty"`
	Input   string `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
}

func (m *RequestContext) Reset()                    { *m = RequestContext{} }
func (m *RequestContext) String() string            { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()               {}
func (*RequestContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestContext) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RequestContext) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RequestContext) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *RequestContext) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type ResponseContext struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Header string `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
}

func (m *ResponseContext) Reset()                    { *m = ResponseContext{} }
func (m *ResponseContext) String() string            { return proto.CompactTextString(m) }
func (*ResponseContext) ProtoMessage()               {}
func (*ResponseContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseContext) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseContext) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *ResponseContext) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestContext)(nil), "pb.RequestContext")
	proto.RegisterType((*ResponseContext)(nil), "pb.ResponseContext")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPC service

type RPCClient interface {
	Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error) {
	out := new(ResponseContext)
	err := grpc.Invoke(ctx, "/pb.RPC/Request", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPC service

type RPCServer interface {
	Request(context.Context, *RequestContext) (*ResponseContext, error)
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RPC/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Request(ctx, req.(*RequestContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RPC_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x8a, 0xc2, 0x30,
	0x14, 0x85, 0xa7, 0xed, 0x34, 0xa5, 0x77, 0x31, 0x03, 0x99, 0xa1, 0x04, 0x57, 0xd2, 0x95, 0xab,
	0x2e, 0xd4, 0x9d, 0xcb, 0xbe, 0x80, 0x64, 0xe7, 0xb2, 0x3f, 0x17, 0x5a, 0xd0, 0x26, 0x26, 0x37,
	0xe2, 0xe3, 0x8b, 0x49, 0x0b, 0x76, 0xf9, 0x7d, 0x81, 0x73, 0x72, 0x2e, 0xe4, 0x46, 0x77, 0x95,
	0x36, 0x8a, 0x14, 0x8f, 0x75, 0x5b, 0x6a, 0xf8, 0x91, 0x78, 0x77, 0x68, 0xa9, 0x56, 0x13, 0xe1,
	0x93, 0xb8, 0x80, 0xcc, 0xa2, 0x79, 0x8c, 0x1d, 0x8a, 0x68, 0x1b, 0xed, 0x72, 0xb9, 0x20, 0x2f,
	0x80, 0xdd, 0x90, 0x06, 0xd5, 0x8b, 0xd8, 0x3f, 0xcc, 0xf4, 0xf6, 0x03, 0x36, 0x3d, 0x1a, 0x91,
	0x04, 0x1f, 0x88, 0xff, 0x43, 0x3a, 0x4e, 0xda, 0x91, 0xf8, 0xf6, 0x3a, 0x40, 0x79, 0x81, 0x5f,
	0x89, 0x56, 0xab, 0xc9, 0xe2, 0x52, 0x59, 0x00, 0xb3, 0xd4, 0x90, 0xb3, 0xbe, 0x31, 0x95, 0x33,
	0x7d, 0x04, 0xc7, 0xab, 0xe0, 0x02, 0x98, 0x41, 0xeb, 0xae, 0xb4, 0x14, 0x06, 0xda, 0x9f, 0x20,
	0x91, 0xe7, 0x9a, 0x1f, 0x21, 0x9b, 0x37, 0x71, 0x5e, 0xe9, 0xb6, 0x5a, 0x0f, 0xdc, 0xfc, 0x05,
	0xb7, 0xfa, 0x42, 0xf9, 0xd5, 0x32, 0x7f, 0x94, 0xc3, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xfe,
	0x8f, 0x11, 0x21, 0x01, 0x00, 0x00,
}
