package context

//1消息（1字头）
const ERR_CONTINUE = 100
const ERR_SWITCHING_PROTOCOLS = 101
const ERR_PROCESSING = 102

//2成功（2字头）
const ERR_OK = 200
const ERR_CREATED = 201
const ERR_ACCEPTED = 202
const ERR_NON_AUTHORITATIVE_INFORMATION = 203
const ERR_NO_CONTENT = 204 //失败
const ERR_RESET_CONTENT = 205
const ERR_PARTIAL_CONTENT = 206
const ERR_MULTI_STATUS = 207

//3重定向（3字头）
const ERR_MULTIPLE_CHOICES = 300
const ERR_MOVED_PERMANENTLY = 301
const ERR_MOVE_TEMPORARILY = 302
const ERR_SEE_OTHER = 303
const ERR_NOT_MODIFIED = 304
const ERR_USE_PROXY = 305
const ERR_SWITCH_PROXY = 306
const ERR_TEMPORARY_REDIRECT = 307

//4请求错误（4字头）
const ERR_BAD_REQUEST = 400 //参数错误
const ERR_UNAUTHORIZED = 401
const ERR_PAYMENT_REQUIRED = 402
const ERR_FORBIDDEN = 403
const ERR_NOT_FOUND = 404
const ERR_METHOD_NOT_ALLOWED = 405
const ERR_NOT_ACCEPTABLE = 406 //缺少必须参数
const ERR_PROXY_AUTHENTICATION_REQUIRED = 407
const ERR_REQUEST_TIMEOUT = 408
const ERR_CONFLICT = 409
const ERR_GONE = 410
const ERR_LENGTH_REQUIRED = 411
const ERR_PRECONDITION_FAILED = 412
const ERR_REQUEST_ENTITY_TOO_LARGE = 413
const ERR_REQUEST_URI_TOO_LONG = 414
const ERR_UNSUPPORTED_MEDIA_TYPE = 415
const ERR_REQUESTED_RANGE_NOT_SATISFIABLE = 416
const ERR_EXPECTATION_FAILED = 417
const ERR_UNPROCESSABLE_ENTITY = 422
const ERR_LOCKED = 423
const ERR_FAILED_DEPENDENCY = 424
const ERR_UNORDERED_COLLECTION = 425
const ERR_UPGRADE_REQUIRED = 426
const ERR_RETRY_WITH = 449
const ERR_UNAVAILABLE_FOR_LEGAL_REASONS = 451

//5服务器错误（5、6字头）
const ERR_SERVER_ERROR = 500 //系统繁忙
const ERR_NOT_IMPLEMENTED = 501
const ERR_BAD_GATEWAY = 502
const ERR_SERVICE_UNAVAILABLE = 503
const ERR_GATEWAY_TIMEOUT = 504
const ERR_HTTP_VERSION_NOT_SUPPORTED = 505
const ERR_constIANT_ALSO_NEGOTIATES = 506
const ERR_INSUFFICIENT_STORAGE = 507
const ERR_BANDWIDTH_LIMIT_EXCEEDED = 509
const ERR_NOT_EXTENDED = 510
const ERR_UNPARSEABLE_RESPONSE_HEADERS = 600

//自定义状态码
const FAILURE = 900 //明确失败
